### ISSUE TITLE
Calls after AddChild() are not added to child

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#6] opened 2015-02-25 01:25 UTC
In this example:

	ContentTypes.Where(c => c.Alias == "Page")
		.AddChild("TestContentType2", p => { p.Icon = "icon-wand color-green"; })
		.AllowUnder("Home");

TestContent2 is not allowed under home. 
Pages is allowed under home.
Is this intentional, it confused me.
I guess this is jquery-like... what would be the recommended way to do what I'm trying to do (basically specify a parent when creating a new content type.

**Comment by ashmind** [comment] 2015-02-25 02:06
This is a good point -- this is by design, but it is also confusing (and there is no `Action<...Syntax>` overload for `AddChild` as well). I'll have to think about it.

If it affects child though, the following will become weird:
```csharp
ContentTypes.Where(c => c.Alias == "Page")
    .AddChild("TestContentType1")
    .AddChild("TestContentType2")
```

I'll think about this.

**Comment by Myster** [comment] 2015-02-25 02:17
I agree with you... I think...
The first thing I tried may be your best solution, it was:

	ContentTypes.Add("x").SetParent("Page").AllowUnder("Home");

**Comment by Myster** [comment] 2015-02-25 02:18
P.S. some brief documentation on `Action<...Syntax>` would be appreciated :-}

**Comment by ashmind** [comment] 2015-02-25 02:23
> P.S. some brief documentation on Action<...Syntax> would be appreciated :-}
Well that would just be
```csharp
ContentTypes.Where(c => c.Alias == "Page")
    .AddChild("TestContentType2", p => p.AllowUnder("Home"))
```

But I don't think we provide such overload at the moment.

> ContentTypes.Add("x").SetParent("Page").AllowUnder("Home");

This is good because it also allows moving existing nodes -- I'll plan this.

My main design question is -- can I prevent people from making a mistake assuming that calls after AddChild go to child. Probably not.

**Comment by Myster** [comment] 2015-02-25 02:50
I don't see how to stop them making that mistake, I guess they figure it out quick enough, I did. :-)

**Comment by ashmind** [comment] 2015-02-25 04:29
Closing this since I split it.

**Closed by ashmind** 2015-02-25 04:29 UTC
Labels: design
